name: travelling_app
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/l.png
    - assets/snow2.png
    - assets/Alley_palace.png
    - assets/Courdes_Alpes.png
    - assets/Aspen_image.png
    - assets/Courdes_Alpes big.png
    - assets/snow.png
    - assets/exp.png
    - assets/f1.jpg
    - assets/f2.jpg
    - assets/f3.webp
    - assets/f5.webp
    - assets/hotel2.jpg
    - assets/hotel4.jpg
    - assets/hotel3.jpg
    - assets/hotel.jpg


  # Fonts
  fonts:
    - family: Hiatus
      fonts:
        - asset: assets/fonts/fonts/Hiatus.otf
        - asset: assets/fonts/fonts/Hiatus.ttf
